receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  attributes:
    actions:
      - key: environment
        value: development
        action: upsert
      - key: service
        value: reminder-api
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: reminder_api

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  otlphttp/tempo:
    endpoint: http://tempo:4318

  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [otlphttp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp/loki, debug]
